import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import { ArchSpec, FileRole, Violation, ViolationState } from "../types";

const SIDECAR_DIR = "arch";

function sidecarPath(rootDir: string, filePath: string): string {
  const rel = path.relative(rootDir, filePath);
  // 패키지 구조를 그대로 유지하며 .md 확장자 추가
  return path.join(rootDir, SIDECAR_DIR, rel + ".md");
}

function writeSidecar(rootDir: string, filePath: string, role: FileRole): void {
  const sp = sidecarPath(rootDir, filePath);
  const dir = path.dirname(sp);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const content = [
    `# Architecture Metadata: ${path.basename(filePath)}`,
    "",
    `- **File Path:** \`${filePath}\``,
    `- **Role:** \`${role.role}\``,
    `- **Layer:** \`${role.layer}\``,
    `- **Bounded Context:** \`${role.boundedContext}\``,
    "",
    "## Dependency Rules",
    `- **Allowed:** ${role.depends.length > 0 ? role.depends.join(", ") : "none"}`,
    `- **Forbidden:** ${role.forbidden.length > 0 ? role.forbidden.join(", ") : "none"}`,
    "",
    "---",
    "> Auto-generated by vibe-arch. This file mirrors the source structure for AI context.",
  ].join("\n");

  fs.writeFileSync(sp, content, "utf-8");
}

export function parseArchComment(
  content: string,
  filePath: string,
): Record<string, string> | null {
  const result: Record<string, string> = {};
  const blockMatch = content.match(/@arch\n([\s\S]*?)@arch-end/);
  if (!blockMatch) return null;

  const lines = blockMatch[1].split("\n");
  lines.forEach((line, idx) => {
    const clean = line.replace(/^\s*(\*|#|\/\/)\s*/, "").trim();
    if (!clean) return;
    const colonIdx = clean.indexOf(":");
    if (colonIdx === -1) {
      console.log(
        `[vibe-arch] [WARN] ${filePath}:@arch+${idx + 1} - malformed line: "${clean}"`,
      );
      console.log(`[vibe-arch] [FIX]  Format should be: key: value`);
      return;
    }
    result[clean.slice(0, colonIdx).trim()] = clean.slice(colonIdx + 1).trim();
  });
  return result;
}

export function generateArchComment(role: FileRole, ext: string): string {
  const lines = [
    `role: ${role.role}`,
    `layer: ${role.layer}`,
    `bounded_context: ${role.boundedContext}`,
  ];
  if (role.depends && role.depends.length > 0)
    lines.push(`depends: [${role.depends.join(", ")}]`);
  if (role.forbidden && role.forbidden.length > 0)
    lines.push(
      `forbidden: [${role.forbidden.map((f) => `${f}.*`).join(", ")}]`,
    );

  if ([".java", ".kt", ".ts", ".tsx", ".js", ".dart", ".swift"].includes(ext)) {
    return `/**\n * @arch\n${lines.map((l) => ` * ${l}`).join("\n")}\n * @arch-end\n */`;
  }
  if (ext === ".py")
    return `# @arch\n${lines.map((l) => `# ${l}`).join("\n")}\n# @arch-end`;
  if (ext === ".go")
    return `// @arch\n${lines.map((l) => `// ${l}`).join("\n")}\n// @arch-end`;
  return `# @arch\n${lines.map((l) => `# ${l}`).join("\n")}\n# @arch-end`;
}

function removeExistingComment(content: string, ext: string): string {
  if ([".java", ".kt", ".ts", ".tsx", ".js", ".dart", ".swift"].includes(ext)) {
    return content.replace(
      /\/\*\*\s*\n[\s\S]*?@arch-end[\s\S]*?\*\/\s*\n*/m,
      "",
    );
  }
  return content.replace(/(#|\/\/) @arch\n[\s\S]*?(#|\/\/) @arch-end\n*/m, "");
}

let isUpdatingClaude = false;
const claudeUpdateQueue: Array<() => Promise<void>> = [];

async function processClaudeQueue() {
  if (isUpdatingClaude || claudeUpdateQueue.length === 0) return;
  isUpdatingClaude = true;
  const task = claudeUpdateQueue.shift();
  if (task) await task();
  isUpdatingClaude = false;
  processClaudeQueue();
}

function hashContent(content: string): string {
  return crypto.createHash("md5").update(content).digest("hex");
}

export function generateClaudeMd(
  spec: ArchSpec,
  recentFile?: string,
  violations?: Violation[],
): string {
  const lines: string[] = [
    "# Architecture Context (auto-generated by vibe-arch)",
    "",
    "## Project",
    `- Architecture: ${spec.architecture}`,
    `- Language: ${spec.language}`,
    `- Bounded Contexts: ${spec.bounded_contexts.length > 0 ? spec.bounded_contexts.join(", ") : "none detected"}`,
    `- Comment Injection: ${spec.comment_injection ?? "enabled"}`,
    "",
    "## AI Behavior Guide",
    "- **Read Metadata First:** Every source file contains an `@arch` ... `@arch-end` metadata block at the top (usually 5-10 lines).",
    "- **Context Awareness:** You MUST read this block before modifying or analyzing a file to ensure compliance with its specific role and layer rules.",
    "- **Integrity:** Do not remove, modify, or corrupt the `@arch` metadata blocks unless explicitly instructed to update the architecture.",
    "",
    "## Layer Rules",
    "",
    "> These rules define allowed dependencies per layer.",
    "> Violations must be fixed by routing through the correct port/interface.",
    "",
  ];

  for (const [layer, rule] of Object.entries(spec.layers)) {
    lines.push(`### ${layer}`);
    if ((rule as any).description) lines.push(`> ${(rule as any).description}`);
    lines.push(
      `- Patterns: ${[...rule.patterns, ...(rule.custom_patterns || [])].join(", ")}`,
    );
    if (rule.forbidden_deps.length > 0)
      lines.push(`- MUST NOT depend on: ${rule.forbidden_deps.join(", ")}`);
    if (rule.allowed_deps.length > 0)
      lines.push(`- May depend on: ${rule.allowed_deps.join(", ")}`);
    else lines.push(`- May depend on: (none - pure layer)`);
    lines.push("");
  }

  if (recentFile) {
    lines.push("## Last Modified");
    lines.push(`- \`${recentFile}\``);
    lines.push("");
  }

  if (violations && violations.length > 0) {
    lines.push("## [ACTION REQUIRED] Architecture Violations");
    lines.push("");
    for (const v of violations) {
      lines.push(`- \`${v.filePath}\`: ${v.message}`);
      lines.push(
        `  - Fix: use a port/interface instead of direct layer reference`,
      );
    }
  } else {
    lines.push("## Status: OK");
    lines.push("No architecture violations detected.");
  }

  lines.push("");
  lines.push("---");
  lines.push("> Auto-managed by vibe-arch. Do not edit manually.");
  return lines.join("\n");
}

export function injectOrUpdateComment(
  filePath: string,
  role: FileRole,
  rootDir?: string,
): void {
  let mode: string = "inline";
  if (rootDir) {
    try {
      const specPath = path.join(rootDir, ".arch-spec.json");
      if (fs.existsSync(specPath)) {
        const spec = JSON.parse(fs.readFileSync(specPath, "utf-8"));
        mode = spec.comment_injection ?? "inline";
      }
    } catch (e) {
      console.error(`[vibe-arch] Error reading spec: ${e}`);
    }
  }

  // 'sidecar' 모드: arch/ 폴더 아래에 패키지 구조 미러링하여 .md 파일 생성
  if (mode === "sidecar" && rootDir) {
    writeSidecar(rootDir, filePath, role);
    return;
  }

  // 'disabled' 모드: 아무 작업 안 함
  if (mode === "disabled") return;

  // 기본값 또는 'inline': 소스 코드 최상단에 주석 주입
  const ext = path.extname(filePath);
  const newComment = generateArchComment(role, ext);

  try {
    if (!fs.existsSync(filePath)) return;
    const originalContent = fs.readFileSync(filePath, "utf-8");
    const cleaned = removeExistingComment(originalContent, ext);
    const updated = newComment + "\n\n" + cleaned.trimStart();
    if (hashContent(originalContent) === hashContent(updated)) return;
    fs.writeFileSync(filePath, updated, "utf-8");
  } catch (e: any) {
    console.error(
      `[vibe-arch] [ERROR] Failed to update comment in ${filePath}: ${e.message}`,
    );
  }
}

export function generateAiMd(
  spec: ArchSpec,
  platformName: string = "AI",
): string {
  const lines: string[] = [
    `# ${platformName} Development Guide (vibe-arch optimized)`,
    "",
    `This project uses \`vibe-arch\` to maintain architectural integrity. ${platformName === "AI" ? "AI models (Gemini, Claude, etc.)" : platformName} MUST follow these instructions.`,
    "",
    "## 1. Architecture Metadata (@arch)",
    "- Every source file contains an `@arch` metadata block at the top.",
    "- This block defines the file's role, layer, and dependency rules.",
    "- **Instruction:** Before modifying or analyzing any file, read this block (usually 5-10 lines) to ensure your changes comply with the project's architecture.",
    "",
    "## 2. Dependency Rules",
    "- `forbidden`: You MUST NOT import or depend on these layers/patterns.",
    "- `depends`: These are the allowed dependencies for this file.",
    "- If your proposed change requires a new dependency, verify it doesn't violate the rules defined in `@arch`.",
    "",
    "## 3. Project Overview",
    `- Architecture: ${spec.architecture}`,
    `- Language: ${spec.language}`,
    `- Bounded Contexts: ${spec.bounded_contexts.join(", ") || "none detected"}`,
    "",
    "---",
    "> Auto-managed by vibe-arch. Do not edit manually.",
  ];
  return lines.join("\n");
}

export function updateAiContexts(
  rootDir: string,
  spec: ArchSpec,
  recentFile?: string,
  violations?: Violation[],
): void {
  const targets =
    spec.ai_targets && spec.ai_targets.length > 0
      ? spec.ai_targets
      : ["CLAUDE.md", "GEMINI.md", "AI.md"];
  for (const targetName of targets) {
    claudeUpdateQueue.push(async () => {
      let newContent: string;
      const upperTarget = targetName.toUpperCase();
      if (upperTarget === "AI.MD") {
        newContent = generateAiMd(spec, "AI");
      } else if (upperTarget === "GEMINI.MD") {
        newContent = generateAiMd(spec, "Gemini");
      } else {
        newContent = generateClaudeMd(spec, recentFile, violations);
      }

      const targetPath = path.join(rootDir, targetName);
      try {
        if (fs.existsSync(targetPath)) {
          const existing = fs.readFileSync(targetPath, "utf-8");
          if (hashContent(existing) === hashContent(newContent)) return;
          if (
            existing.includes("auto-generated by vibe-arch") ||
            existing.includes("Development Guide")
          ) {
            fs.writeFileSync(targetPath, newContent, "utf-8");
          } else {
            const marker = `\n\n<!-- vibe-arch-${targetName} start -->`;
            const endMarker = `<!-- vibe-arch-${targetName} end -->`;
            const regex = new RegExp(
              `\\n\\n<!-- vibe-arch-${targetName} start -->[\\s\\S]*<!-- vibe-arch-${targetName} end -->`,
              "m",
            );
            const cleaned = existing.replace(regex, "");
            fs.writeFileSync(
              targetPath,
              cleaned + marker + "\n" + newContent + "\n" + endMarker,
              "utf-8",
            );
          }
        } else {
          fs.writeFileSync(targetPath, newContent, "utf-8");
        }
      } catch (e) {
        console.error(
          `[vibe-arch] Failed to update context file ${targetName}: ${e}`,
        );
      }
    });
  }
  processClaudeQueue();
}

export function saveViolationState(
  rootDir: string,
  violations: Violation[],
): void {
  const statePath = path.join(rootDir, ".arch-violations.json");
  const summary: Record<string, number> = {};
  for (const v of violations) {
    summary[v.from] = (summary[v.from] || 0) + 1;
  }
  const state: ViolationState = {
    lastUpdated: new Date().toISOString(),
    violations,
    summary,
  };
  try {
    fs.writeFileSync(statePath, JSON.stringify(state, null, 2), "utf-8");
  } catch {}
}

export function loadViolationState(rootDir: string): ViolationState | null {
  const statePath = path.join(rootDir, ".arch-violations.json");
  try {
    return JSON.parse(fs.readFileSync(statePath, "utf-8"));
  } catch {
    return null;
  }
}

export function generateArchSpec(spec: ArchSpec): string {
  const lines: string[] = [
    "# .arch-spec.yaml - auto-generated by vibe-arch",
    `architecture: ${spec.architecture}`,
    `language: ${spec.language}`,
    `root: "${spec.root}"`,
    `comment_injection: ${spec.comment_injection ?? "enabled"}  # enabled | disabled | sidecar`,
    "",
    "bounded_contexts:",
  ];
  if (spec.bounded_contexts.length === 0) {
    lines.push("  [] # none detected");
  } else {
    for (const ctx of spec.bounded_contexts) lines.push(`  - ${ctx}`);
  }
  lines.push("");
  lines.push("layers:");
  for (const [layer, rule] of Object.entries(spec.layers)) {
    lines.push(`  ${layer}:`);
    if ((rule as any).description)
      lines.push(`    # ${(rule as any).description}`);
    lines.push(`    patterns: [${rule.patterns.join(", ")}]`);
    if (rule.custom_patterns && rule.custom_patterns.length > 0) {
      lines.push(
        `    custom_patterns: [${rule.custom_patterns.join(", ")}]  # user-defined`,
      );
    }
    lines.push(`    forbidden_deps: [${rule.forbidden_deps.join(", ")}]`);
    lines.push(`    allowed_deps: [${rule.allowed_deps.join(", ")}]`);
  }
  return lines.join("\n");
}
